import { JobStatus } from '@prisma/client';

export const jobs = [
  {
    title: 'Frontend Developer',
    description: 'Build user interfaces using React and TailwindCSS.',
    location: 'Cairo',
    salary: 15000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Backend Developer',
    description: 'Develop REST APIs using NestJS and PostgreSQL.',
    location: 'Alexandria',
    salary: 17000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Full Stack Developer',
    description: 'Work across both frontend and backend technologies.',
    location: 'Giza',
    salary: 18000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'DevOps Engineer',
    description: 'Maintain CI/CD pipelines and cloud infrastructure.',
    location: 'Remote',
    salary: 20000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Data Scientist',
    description: 'Analyze data and build predictive models.',
    location: 'Remote',
    salary: 22000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'QA Engineer',
    description: 'Perform testing and ensure software quality.',
    location: 'Cairo',
    salary: 14000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Product Manager',
    description: 'Lead product development and roadmap planning.',
    location: 'Remote',
    salary: 23000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'UI/UX Designer',
    description: 'Design user-friendly interfaces and experiences.',
    location: 'Cairo',
    salary: 16000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Mobile Developer',
    description: 'Build mobile apps using Flutter.',
    location: 'Remote',
    salary: 18000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'AI Engineer',
    description: 'Implement AI and machine learning solutions.',
    location: 'Remote',
    salary: 25000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Security Engineer',
    description: 'Ensure application and infrastructure security.',
    location: 'Giza',
    salary: 21000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Technical Writer',
    description: 'Document APIs and developer tools.',
    location: 'Alexandria',
    salary: 13000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Business Analyst',
    description: 'Analyze business requirements and processes.',
    location: 'Cairo',
    salary: 15000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Cloud Engineer',
    description: 'Manage cloud infrastructure (AWS/GCP).',
    location: 'Remote',
    salary: 24000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Support Engineer',
    description: 'Help customers resolve technical issues.',
    location: 'Online',
    salary: 12000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Game Developer',
    description: 'Create games using Unity or Unreal.',
    location: 'Giza',
    salary: 17000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Database Administrator',
    description: 'Design and manage PostgreSQL databases.',
    location: 'Cairo',
    salary: 16000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Network Engineer',
    description: 'Set up and maintain local networks.',
    location: 'Alexandria',
    salary: 15000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Scrum Master',
    description: 'Facilitate agile ceremonies and sprints.',
    location: 'Cairo',
    salary: 19000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
  {
    title: 'Sales Engineer',
    description: 'Support the sales team with technical expertise.',
    location: 'Remote',
    salary: 20000,
    status: JobStatus.OPEN,
    createdById: 1,
  },
];
